// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppBDT.h"
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_bdtDdMod();
RcppExport SEXP _rcpp_module_boot_bdtDtMod();
RcppExport SEXP _rcpp_module_boot_bdtMod();
RcppExport SEXP _rcpp_module_boot_bdtDuMod();
RcppExport SEXP _rcpp_module_boot_bdtPtMod();
RcppExport SEXP _rcpp_module_boot_bdtTzMod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_bdtDdMod", (DL_FUNC) &_rcpp_module_boot_bdtDdMod, 0},
    {"_rcpp_module_boot_bdtDtMod", (DL_FUNC) &_rcpp_module_boot_bdtDtMod, 0},
    {"_rcpp_module_boot_bdtMod", (DL_FUNC) &_rcpp_module_boot_bdtMod, 0},
    {"_rcpp_module_boot_bdtDuMod", (DL_FUNC) &_rcpp_module_boot_bdtDuMod, 0},
    {"_rcpp_module_boot_bdtPtMod", (DL_FUNC) &_rcpp_module_boot_bdtPtMod, 0},
    {"_rcpp_module_boot_bdtTzMod", (DL_FUNC) &_rcpp_module_boot_bdtTzMod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppBDT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
