// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rnc_solver_X
extern "C" SEXP rnc_solver_X(SEXP X, SEXP L, SEXP Y, SEXP lambda, SEXP W);
RcppExport SEXP _netcoh_rnc_solver_X(SEXP XSEXP, SEXP LSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(rnc_solver_X(X, L, Y, lambda, W));
    return rcpp_result_gen;
END_RCPP
}
// rnc_solver_noX
extern "C" SEXP rnc_solver_noX(SEXP L, SEXP Y, SEXP lambda, SEXP W);
RcppExport SEXP _netcoh_rnc_solver_noX(SEXP LSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(rnc_solver_noX(L, Y, lambda, W));
    return rcpp_result_gen;
END_RCPP
}
// rnc_solver_naive
extern "C" SEXP rnc_solver_naive(SEXP X, SEXP L, SEXP Y, SEXP lambda, SEXP W);
RcppExport SEXP _netcoh_rnc_solver_naive(SEXP XSEXP, SEXP LSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(rnc_solver_naive(X, L, Y, lambda, W));
    return rcpp_result_gen;
END_RCPP
}
// rnc_logistic_fit
extern "C" SEXP rnc_logistic_fit(SEXP X, SEXP L, SEXP Y, SEXP lambda, SEXP theta_init, SEXP tol, SEXP max_iter, SEXP verbose);
RcppExport SEXP _netcoh_rnc_logistic_fit(SEXP XSEXP, SEXP LSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP theta_initSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rnc_logistic_fit(X, L, Y, lambda, theta_init, tol, max_iter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rnc_logistic_fit_noX
extern "C" SEXP rnc_logistic_fit_noX(SEXP L, SEXP Y, SEXP lambda, SEXP theta_init, SEXP tol, SEXP max_iter, SEXP verbose);
RcppExport SEXP _netcoh_rnc_logistic_fit_noX(SEXP LSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP theta_initSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rnc_logistic_fit_noX(L, Y, lambda, theta_init, tol, max_iter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rnc_cox_fit
extern "C" SEXP rnc_cox_fit(SEXP X, SEXP L, SEXP Y, SEXP delta, SEXP lambda, SEXP theta_init, SEXP tol, SEXP max_iter, SEXP verbose);
RcppExport SEXP _netcoh_rnc_cox_fit(SEXP XSEXP, SEXP LSEXP, SEXP YSEXP, SEXP deltaSEXP, SEXP lambdaSEXP, SEXP theta_initSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rnc_cox_fit(X, L, Y, delta, lambda, theta_init, tol, max_iter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rnc_cox_fit_noX
extern "C" SEXP rnc_cox_fit_noX(SEXP L, SEXP Y, SEXP delta, SEXP lambda, SEXP theta_init, SEXP tol, SEXP max_iter, SEXP verbose);
RcppExport SEXP _netcoh_rnc_cox_fit_noX(SEXP LSEXP, SEXP YSEXP, SEXP deltaSEXP, SEXP lambdaSEXP, SEXP theta_initSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type L(LSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rnc_cox_fit_noX(L, Y, delta, lambda, theta_init, tol, max_iter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// cox_pll
extern "C" SEXP cox_pll(SEXP eta, SEXP Y, SEXP delta);
RcppExport SEXP _netcoh_cox_pll(SEXP etaSEXP, SEXP YSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_pll(eta, Y, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netcoh_rnc_solver_X", (DL_FUNC) &_netcoh_rnc_solver_X, 5},
    {"_netcoh_rnc_solver_noX", (DL_FUNC) &_netcoh_rnc_solver_noX, 4},
    {"_netcoh_rnc_solver_naive", (DL_FUNC) &_netcoh_rnc_solver_naive, 5},
    {"_netcoh_rnc_logistic_fit", (DL_FUNC) &_netcoh_rnc_logistic_fit, 8},
    {"_netcoh_rnc_logistic_fit_noX", (DL_FUNC) &_netcoh_rnc_logistic_fit_noX, 7},
    {"_netcoh_rnc_cox_fit", (DL_FUNC) &_netcoh_rnc_cox_fit, 9},
    {"_netcoh_rnc_cox_fit_noX", (DL_FUNC) &_netcoh_rnc_cox_fit_noX, 8},
    {"_netcoh_cox_pll", (DL_FUNC) &_netcoh_cox_pll, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_netcoh(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
