// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FWERkControl
List FWERkControl(arma::vec test_stat, arma::mat boot_stat, int k, double alpha);
RcppExport SEXP _StepwiseTest_FWERkControl(SEXP test_statSEXP, SEXP boot_statSEXP, SEXP kSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type test_stat(test_statSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type boot_stat(boot_statSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(FWERkControl(test_stat, boot_stat, k, alpha));
    return rcpp_result_gen;
END_RCPP
}
// FDPControl
List FDPControl(arma::vec test_stat, arma::mat boot_stat, double gamma, double alpha);
RcppExport SEXP _StepwiseTest_FDPControl(SEXP test_statSEXP, SEXP boot_statSEXP, SEXP gammaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type test_stat(test_statSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type boot_stat(boot_statSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(FDPControl(test_stat, boot_stat, gamma, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StepwiseTest_FWERkControl", (DL_FUNC) &_StepwiseTest_FWERkControl, 4},
    {"_StepwiseTest_FDPControl", (DL_FUNC) &_StepwiseTest_FDPControl, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_StepwiseTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
