// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GCPM_cpploss
SEXP GCPM_cpploss(SEXP default_distr_a, SEXP link_function_a, SEXP S_a, SEXP Sigma_a, SEXP W_a, SEXP PD_a, SEXP PL_a, SEXP calc_rc_a, SEXP loss_thr_a, SEXP max_entries_a);
RcppExport SEXP _GCPM_GCPM_cpploss(SEXP default_distr_aSEXP, SEXP link_function_aSEXP, SEXP S_aSEXP, SEXP Sigma_aSEXP, SEXP W_aSEXP, SEXP PD_aSEXP, SEXP PL_aSEXP, SEXP calc_rc_aSEXP, SEXP loss_thr_aSEXP, SEXP max_entries_aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type default_distr_a(default_distr_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type link_function_a(link_function_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type S_a(S_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sigma_a(Sigma_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type W_a(W_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type PD_a(PD_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type PL_a(PL_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type calc_rc_a(calc_rc_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type loss_thr_a(loss_thr_aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_entries_a(max_entries_aSEXP);
    rcpp_result_gen = Rcpp::wrap(GCPM_cpploss(default_distr_a, link_function_a, S_a, Sigma_a, W_a, PD_a, PL_a, calc_rc_a, loss_thr_a, max_entries_a));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP GCPM_cpploss(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_GCPM_GCPM_cpploss", (DL_FUNC) &_GCPM_GCPM_cpploss, 10},
    {"GCPM_cpploss", (DL_FUNC) &GCPM_cpploss, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_GCPM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
