// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// _conditRes
RcppExport SEXP _conditRes(SEXP thetahat, SEXP ysums, SEXP clustsizes, SEXP minidx, SEXP inv, SEXP yin, SEXP Xcent);
RcppExport SEXP _drgee__conditRes(SEXP thetahatSEXP, SEXP ysumsSEXP, SEXP clustsizesSEXP, SEXP minidxSEXP, SEXP invSEXP, SEXP yinSEXP, SEXP XcentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type thetahat(thetahatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ysums(ysumsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type clustsizes(clustsizesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type minidx(minidxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inv(invSEXP);
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xcent(XcentSEXP);
    rcpp_result_gen = Rcpp::wrap(_conditRes(thetahat, ysums, clustsizes, minidx, inv, yin, Xcent));
    return rcpp_result_gen;
END_RCPP
}
// _center
RcppExport SEXP _center(SEXP Uin, SEXP ID);
RcppExport SEXP _drgee__center(SEXP UinSEXP, SEXP IDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Uin(UinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ID(IDSEXP);
    rcpp_result_gen = Rcpp::wrap(_center(Uin, ID));
    return rcpp_result_gen;
END_RCPP
}
