// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// multistate_ddt
// Rcpp::List multistate_ddt(mat P, cube Pu, cube Q, cube Qu);
RcppExport SEXP _rstpm2_multistate_ddt(SEXP PSEXP, SEXP PuSEXP, SEXP QSEXP, SEXP QuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< cube >::type Pu(PuSEXP);
    Rcpp::traits::input_parameter< cube >::type Q(QSEXP);
    Rcpp::traits::input_parameter< cube >::type Qu(QuSEXP);
    rcpp_result_gen = Rcpp::wrap(multistate_ddt(P, Pu, Q, Qu));
    return rcpp_result_gen;
END_RCPP
}
