// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// PMMC
arma::rowvec PMMC(arma::colvec vc_yhat, arma::mat mtx_weight, arma::mat mtx_yobs);
RcppExport SEXP _BaBooN_PMMC(SEXP vc_yhatSEXP, SEXP mtx_weightSEXP, SEXP mtx_yobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type vc_yhat(vc_yhatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mtx_weight(mtx_weightSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mtx_yobs(mtx_yobsSEXP);
    rcpp_result_gen = Rcpp::wrap(PMMC(vc_yhat, mtx_weight, mtx_yobs));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP PMMC(/* FIXME */);

static const R_CallMethodDef CallEntries[] = {
    {"_BaBooN_PMMC", (DL_FUNC) &_BaBooN_PMMC, 3},
    {"PMMC", (DL_FUNC) &PMMC, -1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BaBooN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
