// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ConConPiWiFun.h"
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_mod_cplfunction();
RcppExport SEXP _rcpp_module_boot_mod_cpqfunction();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_mod_cplfunction", (DL_FUNC) &_rcpp_module_boot_mod_cplfunction, 0},
    {"_rcpp_module_boot_mod_cpqfunction", (DL_FUNC) &_rcpp_module_boot_mod_cpqfunction, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ConConPiWiFun(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
