// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppMLPACK.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// kmeans
List kmeans(SEXP data, const int& clusters);
RcppExport SEXP _RcppMLPACK_kmeans(SEXP dataSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const int& >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans(data, clusters));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP RcppMLPACK_kmeans(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_RcppMLPACK_kmeans", (DL_FUNC) &_RcppMLPACK_kmeans, 2},
    {"RcppMLPACK_kmeans", (DL_FUNC) &RcppMLPACK_kmeans, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppMLPACK(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
