// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// emLogit
Rcpp::List emLogit(Rcpp::NumericVector outcome, Rcpp::NumericMatrix prediction, Rcpp::NumericVector W, double tol, int maxIter, double wisdom);
RcppExport SEXP _EBMAforecast_emLogit(SEXP outcomeSEXP, SEXP predictionSEXP, SEXP WSEXP, SEXP tolSEXP, SEXP maxIterSEXP, SEXP wisdomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type prediction(predictionSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type wisdom(wisdomSEXP);
    rcpp_result_gen = Rcpp::wrap(emLogit(outcome, prediction, W, tol, maxIter, wisdom));
    return rcpp_result_gen;
END_RCPP
}
// emNorm
Rcpp::List emNorm(Rcpp::NumericVector outcome, Rcpp::NumericMatrix prediction, Rcpp::NumericMatrix RSQ, Rcpp::NumericVector W, double tol, int maxIter, double wisdom, double sigma2);
RcppExport SEXP _EBMAforecast_emNorm(SEXP outcomeSEXP, SEXP predictionSEXP, SEXP RSQSEXP, SEXP WSEXP, SEXP tolSEXP, SEXP maxIterSEXP, SEXP wisdomSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type prediction(predictionSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type RSQ(RSQSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type wisdom(wisdomSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(emNorm(outcome, prediction, RSQ, W, tol, maxIter, wisdom, sigma2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EBMAforecast_emLogit", (DL_FUNC) &_EBMAforecast_emLogit, 6},
    {"_EBMAforecast_emNorm", (DL_FUNC) &_EBMAforecast_emNorm, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_EBMAforecast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
