// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// crejprob
double crejprob(double pe, double ps, double x1, double n1, double n2, double zalpha);
RcppExport SEXP _STARTdesign_crejprob(SEXP peSEXP, SEXP psSEXP, SEXP x1SEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP zalphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pe(peSEXP);
    Rcpp::traits::input_parameter< double >::type ps(psSEXP);
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type zalpha(zalphaSEXP);
    rcpp_result_gen = Rcpp::wrap(crejprob(pe, ps, x1, n1, n2, zalpha));
    return rcpp_result_gen;
END_RCPP
}
// rejprob
double rejprob(double pe, double ps, double r1, double n1, double n2, double zalpha);
RcppExport SEXP _STARTdesign_rejprob(SEXP peSEXP, SEXP psSEXP, SEXP r1SEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP zalphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pe(peSEXP);
    Rcpp::traits::input_parameter< double >::type ps(psSEXP);
    Rcpp::traits::input_parameter< double >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type zalpha(zalphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rejprob(pe, ps, r1, n1, n2, zalpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STARTdesign_crejprob", (DL_FUNC) &_STARTdesign_crejprob, 6},
    {"_STARTdesign_rejprob", (DL_FUNC) &_STARTdesign_rejprob, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_STARTdesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
