// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_dA();
RcppExport SEXP _rcpp_module_boot_Sda();
RcppExport SEXP _rcpp_module_boot_Rbm();
RcppExport SEXP _rcpp_module_boot_Dbn();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_dA", (DL_FUNC) &_rcpp_module_boot_dA, 0},
    {"_rcpp_module_boot_Sda", (DL_FUNC) &_rcpp_module_boot_Sda, 0},
    {"_rcpp_module_boot_Rbm", (DL_FUNC) &_rcpp_module_boot_Rbm, 0},
    {"_rcpp_module_boot_Dbn", (DL_FUNC) &_rcpp_module_boot_Dbn, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppDL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
