<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<title>CRAN Package Check Results for Package nonneg.cg</title>
<link rel="stylesheet" type="text/css" href="../CRAN_web.css"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body lang="en">
<h2>CRAN Package Check Results for Package <a href="../packages/nonneg.cg/index.html"> nonneg.cg </a> </h2>
<p>
Last updated on 2020-05-04 22:52:58 CEST.
</p>
<table border="1" summary="CRAN check results for package nonneg.cg">
<tr> <th> Flavor </th> <th> Version </th> <th> T<sub>install</sub> </th> <th> T<sub>check</sub> </th> <th> T<sub>total</sub> </th> <th> Status </th> <th> Flags </th> </tr>
<tr> <td>  <a href="check_flavors.html#r-devel-linux-x86_64-debian-clang"> r-devel-linux-x86_64-debian-clang </a> </td> <td> 0.1.6 </td> <td class="r"> 18.65 </td> <td class="r"> 23.20 </td> <td class="r"> 41.85 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-devel-linux-x86_64-debian-gcc"> r-devel-linux-x86_64-debian-gcc </a> </td> <td> 0.1.6 </td> <td class="r"> 12.50 </td> <td class="r"> 18.77 </td> <td class="r"> 31.27 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-devel-linux-x86_64-fedora-clang"> r-devel-linux-x86_64-fedora-clang </a> </td> <td> 0.1.6 </td> <td class="r">  </td> <td class="r">  </td> <td class="r"> 57.87 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-devel-linux-x86_64-fedora-gcc"> r-devel-linux-x86_64-fedora-gcc </a> </td> <td> 0.1.6 </td> <td class="r">  </td> <td class="r">  </td> <td class="r"> 53.46 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-devel-windows-ix86_x86_64"> r-devel-windows-ix86+x86_64 </a> </td> <td> 0.1.6 </td> <td class="r"> 57.00 </td> <td class="r"> 54.00 </td> <td class="r"> 111.00 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-patched-linux-x86_64"> r-patched-linux-x86_64 </a> </td> <td> 0.1.6 </td> <td class="r"> 16.20 </td> <td class="r"> 23.14 </td> <td class="r"> 39.34 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-patched-linux-x86_64/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-patched-solaris-x86"> r-patched-solaris-x86 </a> </td> <td> 0.1.6 </td> <td class="r">  </td> <td class="r">  </td> <td class="r"> 64.20 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-patched-solaris-x86/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-release-linux-x86_64"> r-release-linux-x86_64 </a> </td> <td> 0.1.6 </td> <td class="r"> 15.52 </td> <td class="r"> 23.17 </td> <td class="r"> 38.69 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-release-linux-x86_64/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-release-osx-x86_64"> r-release-osx-x86_64 </a> </td> <td> 0.1.6 </td> <td class="r">  </td> <td class="r">  </td> <td class="r">  </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-release-osx-x86_64/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-release-windows-ix86_x86_64"> r-release-windows-ix86+x86_64 </a> </td> <td> 0.1.6 </td> <td class="r"> 41.00 </td> <td class="r"> 80.00 </td> <td class="r"> 121.00 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-oldrel-osx-x86_64"> r-oldrel-osx-x86_64 </a> </td> <td> 0.1.6 </td> <td class="r">  </td> <td class="r">  </td> <td class="r">  </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-oldrel-osx-x86_64/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
<tr> <td>  <a href="check_flavors.html#r-oldrel-windows-ix86_x86_64"> r-oldrel-windows-ix86+x86_64 </a> </td> <td> 0.1.6 </td> <td class="r"> 38.00 </td> <td class="r"> 67.00 </td> <td class="r"> 105.00 </td> <td> <a href="https://www.R-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/nonneg.cg-00check.html"><span class="check_ok">OK</span></a> </td> <td>  </td> </tr>
</table>
</body>
</html>
