// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// VectorSum
double VectorSum(NumericVector x);
RcppExport SEXP _GiniDistance_VectorSum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(VectorSum(x));
    return rcpp_result_gen;
END_RCPP
}
// VectorVar
double VectorVar(NumericVector x);
RcppExport SEXP _GiniDistance_VectorVar(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(VectorVar(x));
    return rcpp_result_gen;
END_RCPP
}
// orderc
IntegerVector orderc(NumericVector x);
RcppExport SEXP _GiniDistance_orderc(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(orderc(x));
    return rcpp_result_gen;
END_RCPP
}
// ss
NumericMatrix ss(NumericMatrix X_, IntegerVector ind_);
RcppExport SEXP _GiniDistance_ss(SEXP X_SEXP, SEXP ind_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ind_(ind_SEXP);
    rcpp_result_gen = Rcpp::wrap(ss(X_, ind_));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Kernel_Distance
NumericMatrix rcpp_Kernel_Distance(NumericVector x, double sigma);
RcppExport SEXP _GiniDistance_rcpp_Kernel_Distance(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Kernel_Distance(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Eu_distance
NumericMatrix rcpp_Eu_distance(NumericMatrix mat);
RcppExport SEXP _GiniDistance_rcpp_Eu_distance(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Eu_distance(mat));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_covg
double rcpp_covg(NumericVector x, NumericVector y);
RcppExport SEXP _GiniDistance_rcpp_covg(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_covg(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Kcovg
double rcpp_Kcovg(NumericVector x, NumericVector y, double sigma);
RcppExport SEXP _GiniDistance_rcpp_Kcovg(SEXP xSEXP, SEXP ySEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Kcovg(x, y, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Kcovg_alpha
double rcpp_Kcovg_alpha(NumericVector x, NumericVector y, double sigma, double alpha);
RcppExport SEXP _GiniDistance_rcpp_Kcovg_alpha(SEXP xSEXP, SEXP ySEXP, SEXP sigmaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Kcovg_alpha(x, y, sigma, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_covg_alpha
double rcpp_covg_alpha(NumericVector x, NumericVector y, double alpha);
RcppExport SEXP _GiniDistance_rcpp_covg_alpha(SEXP xSEXP, SEXP ySEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_covg_alpha(x, y, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_Covg
double Rcpp_Covg(NumericMatrix x, NumericVector y);
RcppExport SEXP _GiniDistance_Rcpp_Covg(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_Covg(x, y));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_Covg_Alpha
double Rcpp_Covg_Alpha(NumericMatrix x, NumericVector y, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_Covg_Alpha(SEXP xSEXP, SEXP ySEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_Covg_Alpha(x, y, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_KCovg
double Rcpp_KCovg(NumericMatrix x, NumericVector y, double sigma);
RcppExport SEXP _GiniDistance_Rcpp_KCovg(SEXP xSEXP, SEXP ySEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_KCovg(x, y, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_KCovg_Alpha
double Rcpp_KCovg_Alpha(NumericMatrix x, NumericVector y, double sigma, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_KCovg_Alpha(SEXP xSEXP, SEXP ySEXP, SEXP sigmaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_KCovg_Alpha(x, y, sigma, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_gCov
double rcpp_gCov(NumericVector x, NumericVector y);
RcppExport SEXP _GiniDistance_rcpp_gCov(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_gCov(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_gCov_alpha
double rcpp_gCov_alpha(NumericVector x, NumericVector y, double alpha);
RcppExport SEXP _GiniDistance_rcpp_gCov_alpha(SEXP xSEXP, SEXP ySEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_gCov_alpha(x, y, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_gCor_alpha
double rcpp_gCor_alpha(NumericVector x, NumericVector y, double alpha);
RcppExport SEXP _GiniDistance_rcpp_gCor_alpha(SEXP xSEXP, SEXP ySEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_gCor_alpha(x, y, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_gCor
double rcpp_gCor(NumericVector x, NumericVector y);
RcppExport SEXP _GiniDistance_rcpp_gCor(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_gCor(x, y));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_gCov
double Rcpp_gCov(NumericMatrix x);
RcppExport SEXP _GiniDistance_Rcpp_gCov(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_gCov(x));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_gCov_Alpha
double Rcpp_gCov_Alpha(NumericMatrix x, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_gCov_Alpha(SEXP xSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_gCov_Alpha(x, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_KgCov_Alpha
double Rcpp_KgCov_Alpha(NumericMatrix x, double sigma, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_KgCov_Alpha(SEXP xSEXP, SEXP sigmaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_KgCov_Alpha(x, sigma, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_KgCor_Alpha
double Rcpp_KgCor_Alpha(NumericMatrix x, double sigma, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_KgCor_Alpha(SEXP xSEXP, SEXP sigmaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_KgCor_Alpha(x, sigma, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_gCor_Alpha
double Rcpp_gCor_Alpha(NumericMatrix x, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_gCor_Alpha(SEXP xSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_gCor_Alpha(x, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_KgCov
double Rcpp_KgCov(NumericMatrix x, double sigma);
RcppExport SEXP _GiniDistance_Rcpp_KgCov(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_KgCov(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_gCor
double Rcpp_gCor(NumericMatrix x);
RcppExport SEXP _GiniDistance_Rcpp_gCor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_gCor(x));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_KgCor
double Rcpp_KgCor(NumericMatrix x, double sigma);
RcppExport SEXP _GiniDistance_Rcpp_KgCor(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_KgCor(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_gCov
double Rcpp_HatV_gCov(NumericMatrix x);
RcppExport SEXP _GiniDistance_Rcpp_HatV_gCov(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_gCov(x));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_gCov_Alpha
double Rcpp_HatV_gCov_Alpha(NumericMatrix x, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_HatV_gCov_Alpha(SEXP xSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_gCov_Alpha(x, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_gCor_Alpha
double Rcpp_HatV_gCor_Alpha(NumericMatrix x, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_HatV_gCor_Alpha(SEXP xSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_gCor_Alpha(x, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_gCor
double Rcpp_HatV_gCor(NumericMatrix x);
RcppExport SEXP _GiniDistance_Rcpp_HatV_gCor(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_gCor(x));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_KgCov
double Rcpp_HatV_KgCov(NumericMatrix x, double sigma);
RcppExport SEXP _GiniDistance_Rcpp_HatV_KgCov(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_KgCov(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_KgCov_Alpha
double Rcpp_HatV_KgCov_Alpha(NumericMatrix x, double sigma, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_HatV_KgCov_Alpha(SEXP xSEXP, SEXP sigmaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_KgCov_Alpha(x, sigma, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_KgCor
double Rcpp_HatV_KgCor(NumericMatrix x, double sigma);
RcppExport SEXP _GiniDistance_Rcpp_HatV_KgCor(SEXP xSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_KgCor(x, sigma));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_HatV_KgCor_Alpha
double Rcpp_HatV_KgCor_Alpha(NumericMatrix x, double sigma, double alpha);
RcppExport SEXP _GiniDistance_Rcpp_HatV_KgCor_Alpha(SEXP xSEXP, SEXP sigmaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_HatV_KgCor_Alpha(x, sigma, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GiniDistance_VectorSum", (DL_FUNC) &_GiniDistance_VectorSum, 1},
    {"_GiniDistance_VectorVar", (DL_FUNC) &_GiniDistance_VectorVar, 1},
    {"_GiniDistance_orderc", (DL_FUNC) &_GiniDistance_orderc, 1},
    {"_GiniDistance_ss", (DL_FUNC) &_GiniDistance_ss, 2},
    {"_GiniDistance_rcpp_Kernel_Distance", (DL_FUNC) &_GiniDistance_rcpp_Kernel_Distance, 2},
    {"_GiniDistance_rcpp_Eu_distance", (DL_FUNC) &_GiniDistance_rcpp_Eu_distance, 1},
    {"_GiniDistance_rcpp_covg", (DL_FUNC) &_GiniDistance_rcpp_covg, 2},
    {"_GiniDistance_rcpp_Kcovg", (DL_FUNC) &_GiniDistance_rcpp_Kcovg, 3},
    {"_GiniDistance_rcpp_Kcovg_alpha", (DL_FUNC) &_GiniDistance_rcpp_Kcovg_alpha, 4},
    {"_GiniDistance_rcpp_covg_alpha", (DL_FUNC) &_GiniDistance_rcpp_covg_alpha, 3},
    {"_GiniDistance_Rcpp_Covg", (DL_FUNC) &_GiniDistance_Rcpp_Covg, 2},
    {"_GiniDistance_Rcpp_Covg_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_Covg_Alpha, 3},
    {"_GiniDistance_Rcpp_KCovg", (DL_FUNC) &_GiniDistance_Rcpp_KCovg, 3},
    {"_GiniDistance_Rcpp_KCovg_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_KCovg_Alpha, 4},
    {"_GiniDistance_rcpp_gCov", (DL_FUNC) &_GiniDistance_rcpp_gCov, 2},
    {"_GiniDistance_rcpp_gCov_alpha", (DL_FUNC) &_GiniDistance_rcpp_gCov_alpha, 3},
    {"_GiniDistance_rcpp_gCor_alpha", (DL_FUNC) &_GiniDistance_rcpp_gCor_alpha, 3},
    {"_GiniDistance_rcpp_gCor", (DL_FUNC) &_GiniDistance_rcpp_gCor, 2},
    {"_GiniDistance_Rcpp_gCov", (DL_FUNC) &_GiniDistance_Rcpp_gCov, 1},
    {"_GiniDistance_Rcpp_gCov_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_gCov_Alpha, 2},
    {"_GiniDistance_Rcpp_KgCov_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_KgCov_Alpha, 3},
    {"_GiniDistance_Rcpp_KgCor_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_KgCor_Alpha, 3},
    {"_GiniDistance_Rcpp_gCor_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_gCor_Alpha, 2},
    {"_GiniDistance_Rcpp_KgCov", (DL_FUNC) &_GiniDistance_Rcpp_KgCov, 2},
    {"_GiniDistance_Rcpp_gCor", (DL_FUNC) &_GiniDistance_Rcpp_gCor, 1},
    {"_GiniDistance_Rcpp_KgCor", (DL_FUNC) &_GiniDistance_Rcpp_KgCor, 2},
    {"_GiniDistance_Rcpp_HatV_gCov", (DL_FUNC) &_GiniDistance_Rcpp_HatV_gCov, 1},
    {"_GiniDistance_Rcpp_HatV_gCov_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_HatV_gCov_Alpha, 2},
    {"_GiniDistance_Rcpp_HatV_gCor_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_HatV_gCor_Alpha, 2},
    {"_GiniDistance_Rcpp_HatV_gCor", (DL_FUNC) &_GiniDistance_Rcpp_HatV_gCor, 1},
    {"_GiniDistance_Rcpp_HatV_KgCov", (DL_FUNC) &_GiniDistance_Rcpp_HatV_KgCov, 2},
    {"_GiniDistance_Rcpp_HatV_KgCov_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_HatV_KgCov_Alpha, 3},
    {"_GiniDistance_Rcpp_HatV_KgCor", (DL_FUNC) &_GiniDistance_Rcpp_HatV_KgCor, 2},
    {"_GiniDistance_Rcpp_HatV_KgCor_Alpha", (DL_FUNC) &_GiniDistance_Rcpp_HatV_KgCor_Alpha, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GiniDistance(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
